# Generated by Django 4.1.3 on 2022-11-11 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("voting", "0003_voteevent_voteitem_alter_user_username_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_admin",
            field=models.BooleanField(default=False),
        ),
    ]
