# Generated by Django 4.1.3 on 2022-11-11 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("voting", "0004_user_is_admin"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="voteitem",
            options={"verbose_name": "vote item", "verbose_name_plural": "vote items"},
        ),
        migrations.AddField(
            model_name="voteevent",
            name="description",
            field=models.TextField(blank=True, verbose_name="event description"),
        ),
    ]
