# Generated by Django 4.1.3 on 2022-11-11 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("voting", "0005_alter_voteitem_options_voteevent_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="voteevent",
            name="description",
            field=models.TextField(verbose_name="event description"),
        ),
    ]
