# Generated by Django 4.1.3 on 2022-11-11 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("voting", "0008_choicevote"),
    ]

    operations = [
        migrations.AddField(
            model_name="choiceoption",
            name="description",
            field=models.CharField(
                default="choice", max_length=254, verbose_name="description"
            ),
            preserve_default=False,
        ),
    ]
