# Generated by Django 4.1.3 on 2022-11-15 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("voting", "0010_alter_ynavote_choice_alter_ynavote_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="voteitem",
            name="order",
            field=models.PositiveIntegerField(
                db_index=True, default=1, editable=False, verbose_name="order"
            ),
            preserve_default=False,
        ),
    ]
