# Generated by Django 4.1.3 on 2022-11-15 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("voting", "0011_voteitem_order"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="voteitem",
            options={
                "ordering": ("order",),
                "verbose_name": "vote item",
                "verbose_name_plural": "vote items",
            },
        ),
    ]
