# Generated by Django 4.1.3 on 2022-11-16 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("voting", "0012_alter_voteitem_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="voteitem",
            name="detail_link",
            field=models.URLField(blank=True, verbose_name="detail link"),
        ),
    ]
