# Generated by Django 4.1.3 on 2022-11-18 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0013_voteitem_detail_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook_name', models.CharField(max_length=255, verbose_name='facebook name')),
            ],
            options={
                'verbose_name': 'user profile',
                'verbose_name_plural': 'user profiles',
            },
        ),
        migrations.AlterUniqueTogether(
            name='choicevote',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='choicevote',
            name='choice',
        ),
        migrations.RemoveField(
            model_name='choicevote',
            name='user',
        ),
        migrations.RemoveField(
            model_name='multiplechoice',
            name='voteitem_ptr',
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=255, unique=True, verbose_name='username/email'),
        ),
        migrations.DeleteModel(
            name='ChoiceOption',
        ),
        migrations.DeleteModel(
            name='ChoiceVote',
        ),
        migrations.DeleteModel(
            name='MultipleChoice',
        ),
    ]
