# Generated by Django 4.1.3 on 2022-11-18 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0014_userprofile_alter_choicevote_unique_together_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
